[package]
name = "zylo-tiny-skia"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1"
tiny-skia = { version = "0.8", default-features = false, features = [ "std", "simd" ] }
zylo = { path = "../zylo" }
